### ISSUE TITLE
Add a switch to generate test files or not

### ISSUE THREAD

**Issue by spencercjh** [spencercjh/sync-leetcode-today-problem#2]
```yaml
NEED_TEST:
  description: "Whether generate test code snippet"
  default: "True"
  required: false
```
